--[[
    Language Localization: enUS
    Translated by: name <email address>
]]

WIM.AddLocale("enUS", {
    ["WIM (WoW Instant Messenger)"] = true,
    ["_Description"] = "WIM is an addon that brings a familiar feel to communicating through chat in The World of Warcraft. On this screen you will be able to customize WIM to tailor it to your needs.",

    ["_DemoText"] = "This is a demonstration window and is not fully functional. Place this window in the location where you want all other windows to spawn. When finished, you may close this window and your settings will be saved.",

    ["_DateFormat"] = "%m/%d/%Y",

    ["Yes"] = true,
    ["No"] = true,
    ["None"] = true,
    ["Cancel"] = true,
    ["Unknown"] = true,
    ["Click to update..."] = true,
    ["Click to switch between Say, Yell, and Emote."] = true,
    ["Say, Yell, or Emote"] = true,
    ["The message being typed takes the color of the chat type it will send as, like the game's own chat box."] = true,
    ["Battle.net Whispers"] = true,
    ["Filter Editor"] = true,
    ["Draws the frame background only around the filter area, so a clear filter area background (None or Transparent) shows the game world behind the editor."] = true,
    ["Usage"] = true,

    ["state_resting"] = "Resting",
    ["state_combat"] = "Combat",
    ["state_pvp"] = "PVP",
    ["state_arena"] = "Arena",
    ["state_party"] = "Party Instance",
    ["state_raid"] = "Raid Instance",
    ["state_other"] = "Normal (Other)",

    ["Options"] = true,

    ["Up"] = true,
    ["Down"] = true,
    ["Left"] = true,
    ["Right"] = true,
    ["Ignore"] = true,
    ["Block"] = true,
    ["Enable WIM"] = true,

    ["Enable"] = true,
    ["Disable"] = true,

    ["History"] = true,
    ["Filters"] = true,


	["Window Created"] = true,
	["Last Activity"] = true,
    ["Alphabetical"] = true,

    -- Class Names --
    ["Druid"] = LOCALIZED_CLASS_NAMES_MALE.DRUID,
    ["Hunter"] = LOCALIZED_CLASS_NAMES_MALE.HUNTER,
    ["Mage"] = LOCALIZED_CLASS_NAMES_MALE.MAGE,
    ["Paladin"] = LOCALIZED_CLASS_NAMES_MALE.PALADIN,
    ["Priest"] = LOCALIZED_CLASS_NAMES_MALE.PRIEST,
    ["Rogue"] = LOCALIZED_CLASS_NAMES_MALE.ROGUE,
    ["Shaman"] = LOCALIZED_CLASS_NAMES_MALE.SHAMAN,
    ["Warlock"] = LOCALIZED_CLASS_NAMES_MALE.WARLOCK,
    ["Warrior"] = LOCALIZED_CLASS_NAMES_MALE.WARRIOR,
    ["Death Knight"] = LOCALIZED_CLASS_NAMES_MALE.DEATHKNIGHT,
    ["Monk"] = LOCALIZED_CLASS_NAMES_MALE.MONK,
    ["Demon Hunter"] = LOCALIZED_CLASS_NAMES_MALE.DEMONHUNTER,
	["Evoker"] = LOCALIZED_CLASS_NAMES_MALE.EVOKER,

    -- Female Class Names --
    ["DruidF"] = LOCALIZED_CLASS_NAMES_FEMALE.DRUID,
    ["HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.HUNTER,
    ["MageF"] = LOCALIZED_CLASS_NAMES_FEMALE.MAGE,
    ["PaladinF"] = LOCALIZED_CLASS_NAMES_FEMALE.PALADIN,
    ["PriestF"] = LOCALIZED_CLASS_NAMES_FEMALE.PRIEST,
    ["RogueF"] = LOCALIZED_CLASS_NAMES_FEMALE.ROGUE,
    ["ShamanF"] = LOCALIZED_CLASS_NAMES_FEMALE.SHAMAN,
    ["WarlockF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARLOCK,
    ["WarriorF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARRIOR,
    ["Death KnightF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEATHKNIGHT,
    ["MonkF"] = LOCALIZED_CLASS_NAMES_FEMALE.MONK,
    ["Demon HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEMONHUNTER,
	["EvokerF"] = LOCALIZED_CLASS_NAMES_FEMALE.EVOKER,

    ["Game Master"] = true,

    -- WIM.lua --
    ["Toggle WIM 'On' and 'Off'."] = true,

    -- Filters.lua --
    ["Whispers Sent by Addons"] = true,
    ["WhisperSelect Part 1"] = true,
    ["Example Spam Blocker"] = true,
    ["WhisperSelect Part 2"] = true,
    ["Filter Name"] = true,
    ["Filter By"] = true,
    ["Pattern"] = true,
    ["User Type"] = true,
    ["Level"] = true,
    ["Friends"] = true,
    ["Guild Members"] = true,
    ["Party Members"] = true,
    ["Raid Members"] = true,
    ["Cross-Realm"] = true,
    ["Everyone"] = true,
    ["User must be at least level:"] = true,
    ["Apply to messages received."] = true,
    ["Apply to messages sent."] = true,
    ["Apply to:"] = true,
    ["All Classes"] = true,
    ["Action to Perform:"] = true,
    ["Allow"] = true,
    ["Ignore"] = true,
    ["Blocked"] = true,
    ["Save"] = true,
    ["Cancel"] = true,
    ["Edit Filter"] = true,
    ["Add Filter"] = true,

    -- History.lua --
    ["WIM History Button"] = true,
    ["Click to view message history."] = true,
    ["WIM pruned %d |4message:messages; from your history."] = true,
    ["History Viewer"] = true,
    ["Filters"] = true,
    ["Are you sure you want to delete all history saved for %s on %s?"] = true,
    ["Search resulted in %d |4message:messages;."] = true,
    ["No results found!"] = true,
    ["Search"] = true,
    ["Show All"] = true,
    ["Loading History"] = true,
    ["Chat View"] = true,
    ["Text View"] = true,
    ["BBCode"] = true,
    ["WIM History Viewer"] = true,
    ["Display history viewer."] = true,

    -- ldb.lua --
    ["No New Messages"] = true,

    -- Menu.lua --
    ["Whispers"] = true,
    ["Chat"] = true,

    -- Negotiate.lua --
    ["WIM Update Available!"] = true,

    -- ShortcutBar.lua --
    ["Player Location"] = true,
    ["Unknown"] = true,
    ["Click to update..."] = true,
    ["Invite to Party"] = true,
    ["Invite to Guild"] = true,
    ["Add Friend"] = true,
    ["Ignore Player"] = true,
    ["Are you sure you want to\nignore %s?"] = true,
    ["Right-Click for profile links..."] = true,
	["Profile Links"] = true,
	["Location"] = true,
	["Game"] = true,
	["Realm"] = true,
	["Character"] = true,
	["Copy Name"] = true,

    -- Tutorials.lua --
    ["View Updates"] = true,

    -- WhisperEngine.lua --
    ["Whisper Received!"] = true,
    ["Recently Sent Messages"] = true,

    -- Clear.lua --
    ["This action will reload your user interface."] = true,
    ["Do you want to continue?"] = true,
    ["You are about to restore WIM's filters to it's default settings!"] = true,
    ["Usage"] = true,
    ["Clear various WIM data."] = true,

    -- SlashHandler.lua --
    ["WIM Slash Commands"] = true,
    ["Hide or show {all, whisper, chat} windows."] = true,
    ["To see a list of available WIM slash commands type:"] = true,
    ["Display available slash commands."] = true,
    ["Reload User Interface."] = true,

    -- TabHandler.lua --
    ["Manipulating Tabs"] = true,

    -- WindowHandler.lua --
    ["Window Resized!"] = true,
    ["Creating Tab Groups"] = true,
    ["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = true,
    ["Resizing Windows"] = true,
    ["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = true,
    ["Demo Window"] = true,
    ["<Shift-Click> to close window."] = true,
    ["Message Window Hidden"] = true,
    ["Default"] = true,
    ["%s is Away From Keyboard: %s"] = true,
    ["%s does not wish to be disturbed: %s"] = true,
    ["Right-Mouse Click!"] = true,
    ["There might be useful tools hidden under the message box. Right-Click to see them!"] = true,


    -- Options.lua --
    ["Display WIM's options."] = true,
    ["Resetting WIM will clear all of your settings!"] = true,
    ["A reset will reload your user interface."] = true,
    ["Reset all options to default."] = true,

    -- CoreOptions --
    ["Created By:"] = true,
    ["Special Thanks:"] = true,
    ["Enable WIM"] = true,
    ["Credits"] = true,
    ["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = true,
    ["Preview"] = true,
	-- Shorter display text than the key: the full key overflowed the options
	-- panel's right edge (Window Behavior). The key stays untouched so every
	-- other locale keeps its translation.
    ["Window Scale"] = true,
    ["Set Window Spawn Location"] = true,
    ["Up"] = true,
    ["Down"] = true,
    ["Left"] = true,
    ["Right"] = true,
    ["Version"] = true,
    ["Font Outline"] = true,
    ["Thin"] = true,
    ["Thick"] = true,
    ["Allow"] = true,
    ["Ignore"] = true,
    ["Block"] = true,
    ["Protected"] = true,
    ["Action:"] = true,
    ["Occurrences:"] = true,
    ["Delete Filter"] = true,
    ["History"] = true,
    ["Messages"] = true,
    ["Record Chat"] = true,
    ["Maintenance"] = true,
    ["%d |4Week:Weeks;"] = true,
    ["User Level"] = true,
    ["Sounds"] = true,
	["Background"] = BACKGROUND,
	["Low"] = LOW,
	["Medium"] = true,
	["High"] = true,
	["Dialog"] = ENABLE_DIALOG,
	["Tooltip"] = true,

	-- TabManagement.lua --

	-- Talent Specs --
    ["Hybrid"] = true,

    -- Filters.lua --
    ["Show Alert"] = true,
    ["WIM has blocked a message from %s."] = true,
    ["View Blocked Message"] = true,
    ["Blocked Message"] = true,

    -- MinimapIcon.lua
    ["Show Unread Messages"] = true,
    ["Show All Windows"] = true,
    ["Hide All Windows"] = true,

    --Emoticons.lua
    ["Also"] = true,
    ["More"] = true,
    ["Emoticons"] = true,

    --Expose.lua
    ["Your conversations have been hidden in order to clear your screen while in combat. To disable this feature type"] = true,
    ["Expose"] = true,

    --ChatEngine.lua
    ["Have WIM monitor this channel."] = true,
    ["Never Suppress"] = true,
    ["No History"] = true,
    ["World Chat"] = true,
    ["Custom Chat"] = true,
	["Community Chat"] = true,
    ["Chat"] = true,
    ["No Sound"] = true,

    --OffScreenTracker.lua
    ["WIM Window Off Screen"] = true,
    ["Click to reposition."] = true,

	-- Whisper Mode Warnings
	["Set whispers to In-line"] = true,
	["It is recommended for whispers to be set to in-line in order to handle their behavior properly."] = true,

	-- Skins --
	["Blue"] = true,
	["Green"] = true,
	["Red"] = true,
	["Yellow"] = true,

	-- Battle.net friend consolidation (History Viewer)
	["Battle.net Friends"] = true,
	["Are you sure you want to delete ALL history saved with %s, across every realm and every character on this account?"] = true,

	-- Per-date deletion from the History Viewer filter list
	["Are you sure you want to delete the %s history with %s across every realm and character on this account?"] = true,
	["Are you sure you want to delete the %s history for %s across every character on %s?"] = true,
	["Are you sure you want to delete the %s history for %s on %s?"] = true,

    -- Modern options panel --

    -- Modern skin styling --
    ["None (game default)"] = true,
    ["Draws the window frame background only around the message area, so a clear message area background (None or Transparent) shows the game world behind the window."] = true,

    -- Roleplay profiles (Total RP 3 / Mary Sue Protocol) --
    ["Roleplay Profiles"] = true,
    ["Open RP Profile"] = true,
    ["Whisper windows show the selected fields from the partner's Total RP 3 or Mary Sue Protocol profile. Fields left unselected -- or without profile data -- keep the standard display."] = true,
    ["First Name"] = true,
    ["Last Name"] = true,
    ["Title"] = true,
    ["Full Title"] = true,
    ["Race"] = true,
    ["Class"] = true,
    ["Portrait"] = true,
    ["Name & Class Color"] = true,
    ["The profile's first name, shown as the window's name text."] = true,
    ["The profile's last name, shown as the window's name text."] = true,
    ["The short title, shown on the window's details line."] = true,
    ["The long title, shown on the window's details line and portrait tooltip."] = true,
    ["The custom race, replacing the character's race on the details line."] = true,
    ["The custom class, replacing the character's class on the details line."] = true,
    ["The profile's icon, replacing the class icon."] = true,
    ["The profile's custom color, applied to the window's name text and to the class on the details line."] = true,
    ["Apply filter to character menus"] = true,

    -- History Viewer filters --
    ["No Filter"] = true,
    ["Relative Dates"] = true,
    ["%d or more"] = true,
    ["Fewer than %d"] = true,
    ["Results Filtered"] = true,
    ["-- Results Filtered --"] = true,
    ["Results are hidden by the active filter. Click to open the Filters menu."] = true,
    ["Click to change how history is filtered."] = true,
    ["Click to open the Filters menu."] = true,
    ["Clicking the %s button on the message window will show that user's history in WIM's History Viewer."] = true,

    -- Message input & formatting --
    ["Caps how far the input field grows; past the limit the message scrolls inside it."] = true,
    ["The most lines the input field grows to before the message scrolls inside it."] = true,
    ["The input field wraps long messages onto multiple lines, growing downward with the message instead of scrolling it on one line."] = true,
    ["Timestamp Format"] = true,
    ["Bracket Style"] = true,
    ["Colors"] = true,
    ["Sound"] = true,
    ["AaBbYyZz 123"] = true,

    -- Chat type options --
    ["Record"] = true,

    -- Help, bug reports & links --
    ["Found a bug?"] = true,
    ["Report a Bug"] = true,
    ["Reports are welcome! Click below and follow the instructions in the bug report template."] = true,
    ["Show GitHub Link"] = true,
    ["Click to show the link for copying."] = true,
    ["Press Ctrl+C to copy the link, then open it in your browser."] = true,

    -- Debugging & development slash commands --
    ["Clear the captured debug log."] = true,
    ["Set debugging level: /wim debug [0|1|2]. 2 adds verbose chat event tracing."] = true,
    ["Snapshot the next modern context menu while it is open."] = true,
    ["Snapshot UI widget state for skin development: /wim snap all | <Frame.Dot.Path> (bare /wim snap lists the arguments)."] = true,

    -- Tutorials & notices --
    ["WIM is currently running. To access WIM's wide array of options type:"] = true,
    ["WIM's message window has been hidden to WIM's Minimap Icon. If you want to end a conversation, you may do so by <Shift-Clicking> the close button."] = true,
    ["If you want all windows to be this size, you can set the default window size within WIM's options."] = true,
    ["You can <Shift-Click> a tab and drag it out into it's own window."] = true,
    ["You received a whisper which was hidden due to your current activity. You can change how whispers behave in WIM's options by typing"] = true,

    -- Community channel maintenance --
    ["Toggle the experimental community channel re-add repair (mutates chat window channels)."] = true,
    ["Toggle whether WIM focuses community streams at login."] = true,

    -- Misc --
    ["Older Than"] = true,
    ["Users in %s"] = true,

    -- History Viewer filter modes --
    ["Sent by Me"] = true,
    ["Sent by Them"] = true,
    ["Active Days"] = true,
    ["Last 1 Day"] = true,
    ["Last 7 Days"] = true,
    ["Last 30 Days"] = true,
    ["Last 90 Days"] = true,


    -- Chrome background names --
    ["None (fully clear)"] = true,
    ["Transparent"] = true,
    ["Rock"] = true,
    ["Marble"] = true,
    ["Dark Marble"] = true,
    ["Bank"] = true,
    ["Guild Vault"] = true,
    ["Dark Sandstone"] = true,
    ["Parchment (Tileable)"] = true,
    ["Quest Parchment"] = true,
    ["Raid Frame"] = true,
    ["Destiny"] = true,
    ["Stationery (Auction)"] = true,
    ["Stationery (Illustrated)"] = true,
    ["Stationery (Orgrimmar)"] = true,
    ["Stationery (Thunder Bluff)"] = true,
    ["Stationery (Undercity)"] = true,
    ["Stationery (Plain)"] = true,
    ["World Map 1"] = true,
    ["World Map 2"] = true,
    ["Achievement Stats"] = true,
    ["Adventure Map Parchment"] = true,
    ["Collections"] = true,
    ["Frame: Alliance"] = true,
    ["Frame: Horde"] = true,
    ["Frame: Neutral"] = true,
    ["Frame: Marine"] = true,
    ["Frame: Mechagon"] = true,
    ["Frame: Kyrian"] = true,
    ["Frame: Necrolord"] = true,
    ["Frame: Night Fae"] = true,
    ["Frame: Venthyr"] = true,
    ["Frame: Oribos"] = true,
    ["Frame: Dragonflight"] = true,
    ["Frame: The War Within"] = true,
    ["Class Hall"] = true,
    ["Class Hall (Internal)"] = true,
    ["Garrison Landing Page"] = true,
    ["Garrison Mission"] = true,
    ["Ship Mission Parchment"] = true,
    ["Garrison UI"] = true,
    ["Garrison UI 2"] = true,
    ["Credits: Classic"] = true,
    ["Credits: Burning Crusade"] = true,
    ["Credits: Wrath"] = true,
    ["Credits: Cataclysm"] = true,
    ["Credits: Mists of Pandaria"] = true,
    ["Credits: Warlords"] = true,
    ["Credits: Legion"] = true,
    ["Credits: Battle for Azeroth"] = true,


    -- Skin & options style notices --


    -- Slash command feedback --
    ["WIM: community chat settings unavailable."] = true,
    ["WIM community stream auto-focus ON. Takes effect at next login."] = true,
    ["WIM community stream auto-focus OFF - the client may refuse sends to community channels. Takes effect at next login."] = true,
    ["WIM channel re-add repair ON (experimental). On logins where the community stream is focused late, WIM removes and re-adds community channels to ChatFrame1 about 8s after login. If a re-add fails the channel must be restored from the chat settings UI."] = true,
    ["WIM: attempting a repair now (see /wim debug output)."] = true,
    ["WIM channel re-add repair OFF. No further attempts this session."] = true,
    ["WIM: queued options open canceled."] = true,

    -- Modern options, Edit Mode, and dialogs --
    ["%d chat message(s) could not be recovered after the chat lockdown."] = true,
    ["%d unsupported User Level filter(s) were removed."] = true,
    ["/reply Counts Sent Whispers"] = true,
    ["A thin border along the screen edge signals that windows are hidden."] = true,
    ["Above everything, at tooltip level."] = true,
    ["Above most interface frames."] = true,
    ["Above the background layer."] = true,
    ["Actions"] = true,
    ["Addon Compartment Entry"] = true,
    ["All windows hide when combat starts and are restored when it ends."] = true,
    ["Also captures emotes."] = true,
    ["Animates closing windows toward the minimap, and the slide used by combat auto-hide and the show/hide key binding."] = true,
    ["Animation"] = true,
    ["Animation Direction"] = true,
    ["Appearance"] = true,
    ["Applies the filter list below to captured chat messages. Community chat is not filtered."] = true,
    ["Applies to the minimap button, the addon compartment entry, and data broker launchers."] = true,
    ["Applies to whisper and chat history alike. Pruning runs at login."] = true,
    ["Apply To"] = true,
    ["Arrow keys keep controlling the game while the input box has focus; hold Alt to move the text cursor instead."] = true,
    ["At login WIM focuses your community chat streams so the client accepts sends to their channel numbers. Takes effect at the next login and needs at least one channel type captured."] = true,
    ["Auto Focus"] = true,
    ["Backgrounds, input field, and roleplay profile options for the WIM Modern skin."] = true,
    ["Base"] = true,
    ["Battle.net Received"] = true,
    ["Battle.net Sent"] = true,
    ["Behind the standard interface."] = true,
    ["Blizzard is restricting chat right now. Your message was not sent."] = true,
    ["Bracket Names"] = true,
    ["Briefly turns game audio back on so a notification can be heard while all sound is disabled. The Master channel alone cannot get past that setting."] = true,
    ["By conversation name."] = true,
    ["Calculate Minimum Size"] = true,
    ["Cap Stored Messages"] = true,
    ["Capture"] = true,
    ["Capture Community Channels"] = true,
    ["Capture Custom Channels"] = true,
    ["Capture World Channels"] = true,
    ["Capture community channels, set per-channel exceptions, and keep their chat channels working."] = true,
    ["Capture world and custom channels and set per-channel exceptions."] = true,
    ["Cascade Direction"] = true,
    ["Cascade Windows"] = true,
    ["Channels"] = true,
    ["Chat Follows Focus Rules"] = true,
    ["Chat Sounds"] = true,
    ["Chat Types"] = true,
    ["Chat windows join the whisper tab group instead of their own, even while Group Whispers is off."] = true,
    ["Chat windows opened from WIM's menus normally take focus immediately; with this on they follow the pop-up focus rules instead."] = true,
    ["Chat windows share one tabbed window. Does not apply to windows already opened."] = true,
    ["Check to use alternate pop-up rules for this situation. Unchecked, the Base rules apply."] = true,
    ["Choose what WIM captures: whispers, chat types, and channels."] = true,
    ["Clamp to Screen"] = true,
    ["Class-Colored Names"] = true,
    ["Click Hold Limit"] = true,
    ["Click to Release Focus"] = true,
    ["Clickable Links"] = true,
    ["Clicking the game world releases WIM's keyboard focus so movement keys control your character again. Not while in combat."] = true,
    ["Clicks held longer than this are treated as camera turns and keep WIM's focus."] = true,
    ["Combat Auto-Hide"] = true,
    ["Combat hiding only happens inside dungeons, raids, battlegrounds, and arenas."] = true,
    ["Communities"] = true,
    ["Content Background"] = true,
    ["Continuation lines of wrapped messages are indented."] = true,
    ["Conversations"] = true,
    ["Custom %s Rules"] = true,
    ["Custom Channels"] = true,
    ["Custom Rules"] = true,
    ["Defaults"] = true,
    ["Delete"] = true,
    ["Delete All History"] = true,
    ["Delete Old Messages"] = true,
    ["Distinct Chat Sounds"] = true,
    ["Distinct Whisper Sounds"] = true,
    ["Do not play sounds for this channel, whatever the Notifications page plays."] = true,
    ["Do not record history for this channel, whatever History > Recording records."] = true,
    ["Draws the frame background only around the panels, so a clear panel background (None or Transparent) shows the game world behind the viewer."] = true,
    ["Each message is prefixed with the time it arrived."] = true,
    ["Edit Mode"] = true,
    ["Erases every recorded conversation and the archive for every character on this account, then reloads the interface."] = true,
    ["Error Messages"] = true,
    ["Escape Hides Windows"] = true,
    ["Every whisper is recorded."] = true,
    ["Fade When Inactive"] = true,
    ["Fades the window frame, header, and buttons; message and input text stay opaque. Modern skins keep their frame art opaque."] = true,
    ["Filter Chat"] = true,
    ["Filter Panel Background"] = true,
    ["Filter Whispers"] = true,
    ["Filters run top to bottom; the first match wins. Allow lets a message through, Ignore hides it silently, Block hides it and, with Show Alert, tells you in the chat frame with a link to view it."] = true,
    ["Focus & Input"] = true,
    ["Focus Streams at Login"] = true,
    ["Font"] = true,
    ["Font Size"] = true,
    ["Force Blizzard's chat messaging lockdown for testing (on|off, does not persist)."] = true,
    ["Formatting"] = true,
    ["Frame Background"] = true,
    ["Friends & guild"] = true,
    ["Friends and Battle.net friends."] = true,
    ["Friends only"] = true,
    ["Friends, Battle.net friends, and guild members."] = true,
    ["Friends, Battle.net friends, guild members, and your current party and raid get through; whispers from anyone else are ignored. This drives the two WhisperSelect entries in the filter list below."] = true,
    ["Group Chat Windows"] = true,
    ["Group Whispers"] = true,
    ["Group windows into shared tab strips."] = true,
    ["Guild members."] = true,
    ["Guild only"] = true,
    ["Hidden-Windows Indicator"] = true,
    ["Hide During Combat"] = true,
    ["Hide windows during combat and restore them after."] = true,
    ["Hides these messages from the game's chat frame so they appear only in WIM. Per-type and per-channel 'Never Suppress' exceptions on the Conversations pages win. A message is not hidden when no WIM window would show it."] = true,
    ["Hiding"] = true,
    ["Hiding waits until you finish typing your message."] = true,
    ["History Preview Received"] = true,
    ["History Preview Sent"] = true,
    ["Hover Item Tooltips"] = true,
    ["Hovering an item link in a message shows its tooltip without clicking."] = true,
    ["How messages are formatted and displayed."] = true,
    ["Ignore Arrow Keys"] = true,
    ["In-Line Whisper Mode"] = true,
    ["Includes emotes."] = true,
    ["Includes raid warnings."] = true,
    ["Incoming Chat"] = true,
    ["Incoming Whispers"] = true,
    ["Incoming whispers always open in WIM while it is enabled; this additionally redirects typing /w and /r in the game's chat box into a WIM window. Not while in combat."] = true,
    ["Indent Wrapped Lines"] = true,
    ["Indicator"] = true,
    ["Indicator Thickness"] = true,
    ["Input Field"] = true,
    ["Keep Focus"] = true,
    ["Keeps at most this many messages per conversation. Applies to whisper and chat history alike."] = true,
    ["Keeps the keyboard focus in the input box after sending a message."] = true,
    ["Keyboard focus and input behavior."] = true,
    ["Known Senders Only"] = true,
    ["Launcher"] = true,
    ["Launcher Alerts"] = true,
    ["Level with dialog windows."] = true,
    ["Level with most interface frames."] = true,
    ["Limit Height"] = true,
    ["Links & Emoticons"] = true,
    ["Master switch for this channel type; individual channels are captured with the Capture flag below."] = true,
    ["Maximum Lines"] = true,
    ["Menus & Tooltips"] = true,
    ["Message Area Background"] = true,
    ["Message Format"] = true,
    ["Message Windows"] = true,
    ["Message colors."] = true,
    ["Message font, outline, and size."] = true,
    ["Message suppression requires the game's Social > Whisper Mode setting to be In-line; without it, suppressed whispers would vanish into a popout chat tab."] = true,
    ["Messages Received"] = true,
    ["Messages Sent"] = true,
    ["Messages per Conversation"] = true,
    ["Minimap Button"] = true,
    ["Most recently active conversation first."] = true,
    ["Multi-Line Input"] = true,
    ["Native Input Colors"] = true,
    ["Navigation List Background"] = true,
    ["Never Pop Up"] = true,
    ["Never have this window pop-up on my screen. Overrides Windows > Pop-up Rules."] = true,
    ["Never suppress messages from the default chat frame. Overrides 'Show Only in WIM' under Windows > Pop-up Rules."] = true,
    ["New windows that would overlap are offset in the chosen direction. Whisper windows do not cascade while Group Whispers is on, nor chat windows while Group Chat Windows is on. Applies to windows opened after the change."] = true,
    ["No one (GM whispers only)"] = true,
    ["Nothing is recorded except game master whispers."] = true,
    ["Notifications"] = true,
    ["Oldest conversation first."] = true,
    ["Only While in an Instance"] = true,
    ["Open History Viewer"] = true,
    ["Opens a placement window; drag it to where new windows should appear, then close it to save the spot."] = true,
    ["Opens the window when a message arrives in this situation."] = true,
    ["Opens the window when you send a message in this situation."] = true,
    ["Optional different sounds for whispers from particular senders."] = true,
    ["Optional different sounds per chat type."] = true,
    ["Outline for the message area and input box text."] = true,
    ["Override Muted Audio"] = true,
    ["Placement & Size"] = true,
    ["Playback"] = true,
    ["Player names take their class color. Applies to new messages."] = true,
    ["Plays a distinct sound for raid chat instead of the standard incoming sound; raid warnings keep the standard sound. It never mutes."] = true,
    ["Plays a distinct sound for this chat type instead of the standard incoming sound; it never mutes. Use a channel's No Sound flag or turn off incoming chat sounds to silence."] = true,
    ["Plays a sound when a captured chat message arrives. Per-channel No Sound flags on the channel lists mute individual channels."] = true,
    ["Plays a sound when a whisper arrives."] = true,
    ["Plays a sound when you send a message in a captured chat type, from WIM or the game's chat box."] = true,
    ["Plays a sound when you send a whisper."] = true,
    ["Plays notification sounds on the Master channel so they are heard even when sound effects are turned off."] = true,
    ["Plays this sound instead of the standard incoming whisper sound."] = true,
    ["Pop Up on Receive"] = true,
    ["Pop Up on Send"] = true,
    ["Pop-up Rules"] = true,
    ["Pressing Escape hides all open WIM windows."] = true,
    ["Pressing Tab in a whisper window jumps to the next person you whispered. While enabled, forward Tab no longer cycles through window tabs."] = true,
    ["Preview Count"] = true,
    ["Preview Recent Messages"] = true,
    ["Plays this sound instead of the standard incoming whisper sound when a Battle.net friend whispers. When several match, Battle.net friend wins over friend and guild member."] = true,
    ["Privacy & Filtering"] = true,
    ["Profile Fields"] = true,
    ["Puts the keyboard focus in the input box when a window pops up."] = true,
    ["Re-adds community channels to your chat frames when the client drops them, once per login after a late stream focus; /wim channelrepair runs it now. Opt-in: this mutates saved chat window configuration."] = true,
    ["Record From"] = true,
    ["Record Whispers"] = true,
    ["Recording"] = true,
    ["Recording stops as soon as this is off; the history button stays on open windows until the next reload."] = true,
    ["Redirect /w and /r to WIM"] = true,
    ["Repair Dropped Channels"] = true,
    ["Reset Position"] = true,
    ["Retention"] = true,
    ["Retention caps, preview, and deletion."] = true,
    ["Right-Click Opens Unread"] = true,
    ["Runs the whisper filter list below. While off, addon-spam whispers open windows like any other whisper."] = true,
    ["See-Through Frame"] = true,
    ["Sender Details"] = true,
    ["Sent Chat"] = true,
    ["Sent Whispers"] = true,
    ["Separate Friends Group"] = true,
    ["Separate Guild Group"] = true,
    ["Set to In-line"] = true,
    ["Share Tab Group with Whispers"] = true,
    ["Shortcut Bar"] = true,
    ["Show Only in WIM"] = true,
    ["Show Roleplay Profiles"] = true,
    ["Show Timestamps"] = true,
    ["Show WIM Tooltips"] = true,
    ["Show an unread message badge on the WIM launcher icons."] = true,
    ["Show an unread message badge on the WIM launcher icons. Off by default for channels."] = true,
    ["Shows help tooltips on WIM's windows, lists, and the custom rows of these options."] = true,
    ["Shows the most recent messages when a window opens. Applies to whisper and chat history alike, and requires Record Whispers."] = true,
    ["Shows the row of shortcut buttons on message windows. Turning this off takes effect after the next interface reload."] = true,
    ["Shows the sender's class, level, and guild on their window. Sends one /who lookup when the window opens. Applies to windows opened after the change."] = true,
    ["Situations without custom rules follow these base rules."] = true,
    ["Skin"] = true,
    ["Skin default"] = true,
    ["Skin, fonts, message look, and colors."] = true,
    ["Sort Menu by Activity"] = true,
    ["Sort Tabs By"] = true,
    ["Sounds for whispers and chat, and how they are played."] = true,
    ["Sources"] = true,
    ["Storage"] = true,
    ["System Messages & Timestamps"] = true,
    ["Tab Groups"] = true,
    ["Tab to Next Whisper"] = true,
    ["Text smileys render as icons."] = true,
    ["The base rules. Situations without custom rules follow these."] = true,
    ["The button can then be dragged anywhere on the screen."] = true,
    ["The direction windows slide out when they hide. Also used by the show/hide key binding. Only applies while Window Animations is on under Appearance > Skin."] = true,
    ["The interface layer WIM windows draw on; higher layers cover lower ones."] = true,
    ["The message area renders two points larger than the chosen size; the input box and header follow the skin."] = true,
    ["The message box at the bottom of each window."] = true,
    ["The message history window."] = true,
    ["The skin and window chrome."] = true,
    ["The skin picks the font."] = true,
    ["The sound to play. The speaker button plays a preview."] = true,
    ["The whisper and chat windows."] = true,
    ["The window for adding and editing whisper and chat filters."] = true,
    ["These settings style WIM's modern-only skins (such as WIM Modern), which are built from the game's own interface art. They are available while a modern-only skin is selected on the Skin page; with a classic skin active they are greyed out."] = true,
    ["Timestamps"] = true,
    ["Total RP 3 and Mary Sue Protocol profile display on whisper windows."] = true,
    ["Type %s to confirm."] = true,
    ["Unlock Minimap Button"] = true,
    ["Use Master Sound Channel"] = true,
    ["WIM Message Window"] = true,
    ["WIM Modern Skin"] = true,
    ["WIM manages this chat type in its own message windows. Turning a type off stops capture now; its window button stays until the next reload."] = true,
    ["WIM's launcher menus list the most recently active conversations first."] = true,
    ["WIM: the options UI is not available on this client."] = true,
    ["Wait While Typing"] = true,
    ["Web Addresses"] = true,
    ["Web addresses in messages become clickable links."] = true,
    ["What WIM takes over: whispers, and the chat types that get their own windows."] = true,
    ["What is kept, and for how long."] = true,
    ["When choosing the /reply target, your most recent sent whisper counts as well as the last one received."] = true,
    ["When windows appear, where they sit, and what has keyboard focus."] = true,
    ["When windows pop up and when messages leave the chat frame, per situation."] = true,
    ["Where new windows appear, their default size and scale, and the placement of the History Viewer and filter editor are set in the game's Edit Mode."] = true,
    ["Which whispers and chat types are recorded."] = true,
    ["While in a battleground."] = true,
    ["While in a dungeon."] = true,
    ["While in a raid instance."] = true,
    ["While in an arena match."] = true,
    ["While in combat."] = true,
    ["While resting in an inn or city."] = true,
    ["Whisper Sounds"] = true,
    ["Whisper windows opened from WIM's menus normally take focus immediately; with this on they follow the pop-up focus rules instead."] = true,
    ["Whisper windows share one tabbed window. Does not apply to windows already opened."] = true,
    ["Whisper windows show roleplay profile fields from Total RP 3 or any Mary Sue Protocol addon, and gain an Open RP Profile button on their shortcut bar that opens the partner's profile in the installed viewer. Requires the WIM Modern skin."] = true,
    ["Whispers Follow Focus Rules"] = true,
    ["Whispers from friends group into their own tabbed window."] = true,
    ["Whispers from game masters are always recorded. Battle.net whispers count as friends."] = true,
    ["Whispers from guild members group into their own tabbed window. A friend who is also a guild member goes to the friends group."] = true,
    ["Who gets through."] = true,
    ["Window Animations"] = true,
    ["Window Layer"] = true,
    ["Window Opacity"] = true,
    ["Window Skin"] = true,
    ["Where new windows spawn and how big they are, their layer, cascading, and screen clamping."] = true,
    ["Windows"] = true,
    ["Windows Opened from Menus"] = true,
    ["Windows cannot be dragged past the screen edges."] = true,
    ["Windows fade to half opacity after two seconds without the mouse over them."] = true,
    ["World Channels"] = true,
    ["Wraps player names in brackets."] = true,
    ["You are about to permanently delete WIM's message history for every character on this account."] = true,
    ["instant"] = true,
    ["slow"] = true,
    ["Community chat cannot be recorded, so this is always on for community channels."] = true,
    ["Width"] = true,
    ["Height"] = true,
    ["WIM Filter Editor"] = true,
});
