--[[
    Language Localization: trTR
    Translated by: Hakan YILMAZ <hknylmz@msn.com>
]]

local translations = {
    ["WIM (WoW Instant Messenger)"] = true,
    ["_Description"] = "WIM, World of Warcraft'ta sohbet yoluyla iletişim kurmaya alışılmış bir deneyim kazandıran bir eklentidir. Bu ekranda WIM'i ihtiyaçlarınıza göre özelleştirebileceksiniz.",

    ["_DemoText"] = "Bu bir tanıtım penceresidir ve tam olarak işlevsel değildir. Bu pencereyi diğer tüm pencerelerin ortaya çıkmasını istediğiniz konuma yerleştirin. İşiniz bittiğinde, bu pencereyi kapatabilirsiniz ve ayarlarınız kaydedilecektir.",

    ["_DateFormat"] = "%d/%m/%Y",

    ["Yes"] = "Evet",
    ["No"] = "Hayır",
    ["None"] = "Yok",
    ["<Right-Click>"] = "<Sağ-Tıkla>",
    ["<Left-Click>"] = "<Sol-Tıkla>",
    ["OK"] = "Tamam",
    ["Cancel"] = "İptal",
    ["Unknown"] = "Bilinmiyor",
    ["Click to update..."] = "Güncelleme için tıklayın...",
    ["Usage"] = "Kullanım",

    ["state_resting"] = "Dinlenme",
    ["state_combat"] = "Mücadele",
    ["state_pvp"] = "PVP",
    ["state_arena"] = "Arena",
    ["state_party"] = "Parti Durumu",
    ["state_raid"] = "Baskın Durumu",
    ["state_other"] = "Normal (Diğer)",

    ["<Shift-Click> to close window."] = "Pencereyi kapatmak için <Shift-Tıkla>.",

    ["A new version of WIM is available!\nYou can download the latest version by going to:\n\n http://www.wimaddon.com"] = "WIM'in yeni bir sürümü mevcuttur!\nEn son sürümü şu adrese giderek indirebilirsiniz:\n\n http://www.wimaddon.com",

    ["Options"] = "Seçenekler",

    ["Icon Position"] = "Simge Konumu",
    ["Font Size"] = "Yazı Tipi Boyutu",
    ["Window Scale (Percent)"] = "Pencere Ölçeği (Yüzde)",
    ["Transparency (Percent)"] = "Şeffaflık (Yüzde)",
    ["Window Width"] = "Pencere Genişliği",
    ["Window Height"] = "Pencere Yüksekliği",
    ["(Limited by shortcut bar)"] = "(Kısayol çubuğu ile sınırlı)",
    ["ERROR"] = "HATA",
    ["Invalid Name!"] = "Geçersiz isim!",
    ["Name is already used!"] = "İsim zaten kullanılıyor!",
    ["Invalid Alias!"] = "Geçersiz Takma Ad!",
    ["Invalid Keyword/Phrase!"] = "Geçersiz Anahtar Kelime/İfade!",
    ["Keyword/Phrase is already used!"] = "Anahtar kelime/ifade zaten kullanılıyor!",

    ["Day"] = "Gün",
    ["Week"] = "Hafta",
    ["Month"] = "Ay",
    ["Drag to set default spawn/position for message windows."] = "Mesaj pencereleri için varsayılan konumu ayarlamak için sürükleyin.",
    ["Up"] = "Yukarı",
    ["Down"] = "Aşağı",
    ["Left"] = "Sol",
    ["Right"] = "Sağ",
    ["Ignore"] = "Yoksay",
    ["Block"] = "Engel",
    ["Enable WIM"] = "WIM'i Etkinleştir",

    ["Auto Close Friends after:"] = "Sonra, arkadaş mesajlarını otomatik olarak kapat:",
    ["Auto Close Non-Friends after:"] = "Sonra, arkadaşınızdan olmayan mesajları otomatik olarak kapatın:",

    ["Display"] = "Ekran",
    ["Incoming Messages"] = "Gelen Mesajlar",
    ["Outgoing Messages"] = "Giden Mesajlar",
    ["System Messages"] = "Sistem Mesajları",
    ["Error Messages"] = "Hata Mesajları",
    ["Web URLs"] = "Web URL'leri",
    ["Enable"] = "Etkinlestir:",
    ["Disable"] = "Devredısı:",
    ["Enabled"] = "Etkin",
    ["Disabled"] = "Devre dışı",
    ["Display character information."] = "Karakter bilgilerini görüntüleyin.",
    ["Display time stamps"] = "Zaman damgalarını görüntüleme",
    ["This setting limits the\nwindow's minimum height."] = "Bu ayar pencerenin minimum yüksekliğini sınırlar.",
    ["Requires /who querying."] = "/who sorgulaması gerektirir.",
    ["Enable window fading effects."] = "Pencere solma efektlerini etkinleştir.",
    ["Enable window animations."] = "Pencere animasyonlarını etkinleştir.",

    ["Display minimap icon."] = "Mini harita simgesini görüntüle.",

    ["General"] = "Genel",
    ["History"] = "Geçmiş",
    ["Filters"] = "Filtreler",
    ["Plugins"] = "Eklentiler",

    ["Auto focus when window is shown."] = "Pencere gösterildiğinde otomatik odaklanma.",
    ["Preserve focus after sending messages."] = "Mesaj gönderdikten sonra odağı koru.",
    ["Display tooltips."] = "Araç ipuçlarını görüntüleyin.",
    ["Show window when sending a message."] = "Mesaj gönderirken pencereyi göster.",
    ["Show window when message has been received."] = "Mesaj alındığında pencereyi göster.",
    ["Supress messages from default chat frame."] = "Varsayılan sohbet çerçevesinden mesajları bastırın.",
    ["Play sound when message is received."] = "Mesaj alındığında ses çal.",
    ["Play sound when message is sent."] = "Mesaj gönderildiğinde ses çal.",
    ["Sort alphabetically."] = "Alfabetik olarak sırala.",
    ["Use <Escape> to close windows."] = "Pencereleri kapatmak için <Escape> kullanın.",
    ["Windows will close when opening the world map."] = "Dünya haritası açıldığında pencereler kapanacaktır.",
    ["Intercept slash commands."] = "/ komutlarını engelle.",
    ["Ignore arrow keys while typing."] = "Yazarken ok tuşlarını yoksay.",
    ["Requires using <Alt> to navigate text."] = "Metinde gezinmek için <Alt> tuşunu kullanmayı gerektirir.",
    ["Display emoticons."] = "İfadeleri görüntüleyin.",
    ["Display URLs as item links."] = "URL'leri öğe bağlantıları olarak görüntüleyin.",
    ["Display floating item links."] = "Kayan öğe bağlantılarını görüntüleyin.",

    ["Cascade windows."] = "Kademeli pencereler.",
    ["Direction:"] = "Yön:",
    ["Tabs"] = "Sekmeler",
    ["Sort tabs by:"] = "Sekmeleri sırala:",
    ["Alphabetical"] = "Alfabetik",
    ["Recent Activity"] = "Son Aktivite",
    ["Keep windows on top of your UI."] = "Pencereleri kullanıcı arayüzünüzün üstünde tutun.",

    ["Enable/Disable addon messages."] = "Eklenti mesajlarını etkinleştirin/devre dışı bırakın.",

    -- Class Names --
    ["Druid"] = LOCALIZED_CLASS_NAMES_MALE.DRUID,
    ["Hunter"] = LOCALIZED_CLASS_NAMES_MALE.HUNTER,
    ["Mage"] = LOCALIZED_CLASS_NAMES_MALE.MAGE,
    ["Paladin"] = LOCALIZED_CLASS_NAMES_MALE.PALADIN,
    ["Priest"] = LOCALIZED_CLASS_NAMES_MALE.PRIEST,
    ["Rogue"] = LOCALIZED_CLASS_NAMES_MALE.ROGUE,
    ["Shaman"] = LOCALIZED_CLASS_NAMES_MALE.SHAMAN,
    ["Warlock"] = LOCALIZED_CLASS_NAMES_MALE.WARLOCK,
    ["Warrior"] = LOCALIZED_CLASS_NAMES_MALE.WARRIOR,
    ["Death Knight"] = LOCALIZED_CLASS_NAMES_MALE.DEATHKNIGHT,
    ["Monk"] = LOCALIZED_CLASS_NAMES_MALE.MONK,
    ["Demon Hunter"] = LOCALIZED_CLASS_NAMES_MALE.DEMONHUNTER,
	["Evoker"] = LOCALIZED_CLASS_NAMES_MALE.EVOKER,

    -- Female Class Names --
    ["DruidF"] = LOCALIZED_CLASS_NAMES_FEMALE.DRUID,
    ["HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.HUNTER,
    ["MageF"] = LOCALIZED_CLASS_NAMES_FEMALE.MAGE,
    ["PaladinF"] = LOCALIZED_CLASS_NAMES_FEMALE.PALADIN,
    ["PriestF"] = LOCALIZED_CLASS_NAMES_FEMALE.PRIEST,
    ["RogueF"] = LOCALIZED_CLASS_NAMES_FEMALE.ROGUE,
    ["ShamanF"] = LOCALIZED_CLASS_NAMES_FEMALE.SHAMAN,
    ["WarlockF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARLOCK,
    ["WarriorF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARRIOR,
    ["Death KnightF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEATHKNIGHT,
    ["MonkF"] = LOCALIZED_CLASS_NAMES_FEMALE.MONK,
    ["Demon HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEMONHUNTER,
	["EvokerF"] = LOCALIZED_CLASS_NAMES_FEMALE.EVOKER,

    ["Game Master"] = "Oyun Yöneticisi",

    -- WIM.lua --
    ["Toggle WIM 'On' and 'Off'."] = "WIM 'Açık' ve 'Kapalı' arasında geçiş yapın.",
    ["Toggle Debugging Mode 'On' and 'Off'."] = "Hata Ayıklama Modu 'Açık' ve 'Kapalı' arasında geçiş yapın.",
    ["WIM is currently running. To access WIM's wide array of options type:"] = "WIM şu anda çalışıyor. WIM'in geniş seçenek alanına erişmek için yazın:",

    -- Filters.lua --
    ["Whispers Sent by Addons"] = "Eklentiler Tarafından Gönderilen Fısıltılar",
    ["WhisperSelect Part 1"] = "FısıltıSeçimi Bölüm 1",
    ["Example Spam Blocker"] = "Örnek Spam Engelleyici",
    ["WhisperSelect Part 2"] = "FısıltıSeçimi Bölüm 2",
    ["Filter Name"] = "Filtre Adı",
    ["Filter By"] = "Filtreye Göre",
    ["Pattern"] = "Desen",
    ["User Type"] = "Kullanıcı Tipi",
    ["Level"] = "Seviye",
    ["Friends"] = "Arkadaşlar",
    ["Guild Members"] = "Guild Üyeleri",
    ["Party Members"] = "Parti Üyeleri",
    ["Raid Members"] = "Baskın Üyeleri",
    ["Cross-Realm"] = "Çapraz-Realm",
    ["Everyone"] = "Herkes",
    ["User must be at least level:"] = "Kullanıcı en az seviye olmalıdır:",
    ["Apply to messages received."] = "Alınan mesajlar için geçerlidir.",
    ["Apply to messages sent."] = "Gönderilen mesajlara uygulanır.",
    ["Action to Perform:"] = "Gerçekleştirilecek Eylem:",
    ["Allow"] = "İzin ver",
    ["Ignore"] = "Yoksay",
    ["Blocked"] = "Engellendi",
    ["Save"] = "Kaydet",
    ["Cancel"] = "İptal",
    ["Edit Filter"] = "Filtreyi Düzenle",
    ["Add Filter"] = "Filtre Ekle",

    -- History.lua --
    ["WIM History Button"] = "WIM Geçmiş Düğmesi",
    ["Clicking the %s button on the message window will show that user's history in WIM's History Viewer."] = "Mesaj penceresindeki %s düğmesine tıklamak, WIM'in Geçmiş Görüntüleyicisinde o kullanıcının geçmişini gösterecektir.",
    ["Click to view message history."] = "Mesaj geçmişini görüntülemek için tıklayın.",
    ["WIM pruned %d |4message:messages; from your history."] = "WIM geçmişinizden %d |4message:messages;'ı çıkardı.",
    ["History Viewer"] = "Geçmis Görüntüleyici",
    ["Filters"] = "Filtreler",
    ["Are you sure you want to delete all history saved for %s on %s?"] = "%s'de %s için kaydedilen tüm geçmişi silmek istediğinizden emin misiniz?",
    ["Search resulted in %d |4message:messages;."] = "Arama %d ile sonuçlandı |4message:messages;.",
    ["No results found!"] = "Hiçbir sonuç bulunamadı!",
    ["Search"] = "Arama",
    ["Show All"] = "Tümünü Göster",
    ["Loading History"] = "Yükleme Geçmişi",
    ["Chat View"] = "Sohbet Görünümü",
    ["Text View"] = "Metin Görünümü",
    ["WIM History Viewer can be accessed any time by typing:"] = "WIM Geçmiş Görüntüleyicisine istenildiği zaman yazılarak erişilebilir:",
    ["WIM History Viewer"] = "WIM Geçmiş Görüntüleyici",
    ["Display history viewer."] = "Geçmiş görüntüleyiciyi görüntüle.",

    -- ldb.lua --
    ["No New Messages"] = "Yeni Mesaj Yok",

    -- Menu.lua --
    ["Whispers"] = "Fısıltılar",
    ["Chat"] = "Sohbet",

    -- Negotiate.lua --
    ["WIM Update Available!"] = "WIM Güncellemesi Mevcut!",
    ["There is a newer version of WIM available for download. You can download it at %s."] = "WIM'in daha yeni bir sürümü indirilebilir. Bunu %s adresinden indirebilirsiniz.",

    -- ShortcutBar.lua --
    ["Player Location"] = "Oyuncu Konumu",
    ["Unknown"] = "Bilinmiyor",
    ["Click to update..."] = "Güncellemek için tıklayın...",
    ["Coordinates"] = "Koordinatlar",
    ["Invite to Party"] = "Partiye Davet Et",
    ["Add Friend"] = "Arkadaş Ekle",
    ["Ignore User"] = "Kullanıcıyı Yoksay",
    ["Are you sure you want to\nignore %s?"] = "%s engellenecek emin misiniz?",
    ["Right-Click for profile links..."] = "Profil bağlantıları için sağ tıklayın...",
    ["Profile Links"] = "Profil Bağlantıları",
    ["Location"] = "Konum",
    ["Game"] = "Oyun",
    ["Realm"] = "Realm",
    ["Character"] = "Karakter",

    -- Tutorials.lua --
    ["Display WIM tips"] = "WIM ipuçlarını görüntüle",

    -- W2W.lua --
    ["%s is typing..."] = "%s yazıyor...",
    ["W2W Profile"] = "W2W Profil",
    ["Talent Spec"] = "Yetenek Özellikleri",

    -- WhisperEngine.lua --
    ["Whisper Received!"] = "Fısıltı Alındı!",
    ["You received a whisper which was hidden due to your current activity. You can change how whispers behave in WIM's options by typing"] = "Mevcut etkinliğiniz nedeniyle gizlenmiş olan bir fısıltı aldınız. Fısıltıların nasıl davranacağını WIM'in seçeneklerinde şunları yazarak değiştirebilirsiniz",
    ["Recently Sent Messages"] = "Son Gönderilen Mesajlar",

    -- Clear.lua --
    ["You are about to clear all of WIM's history!"] = "WIM'in tüm geçmişini temizlemek üzeresiniz!",
    ["This action will reload your user interface."] = "Bu işlem kullanıcı arayüzünüzü yeniden yükleyecektir.",
    ["Do you want to continue?"] = "Devam etmek istiyor musunuz?",
    ["You are about to restore WIM's filters to it's default settings!"] = "WIM'in filtrelerini varsayılan ayarlarına geri yüklemek üzeresiniz!",
    ["Usage"] = "Kullanım",
    ["Clear various WIM data."] = "Çeşitli WIM verilerini temizleyin.",

    -- SlashHandler.lua --
    ["WIM Slash Commands"] = "WIM / Komutları",
    ["To see a list of available WIM slash commands type:"] = "Kullanılabilir WIM / komutlarının bir listesini görmek için yazın:",
    ["Display available slash commands."] = "Kullanılabilir / komutlarını görüntüle.",
    ["Reload User Interface."] = "Kullanıcı Arayüzünü Yeniden Yükle.",

    -- TabHandler.lua --
    ["Manipulating Tabs"] = "Sekmeleri Yönetme",
    ["You can <Shift-Click> a tab and drag it out into it's own window."] = "Bir sekmeye <Shift ile tıklayabilir> ve kendi penceresine sürükleyebilirsiniz.",

    -- WindowHandler.lua --
    ["Window Resized!"] = "Pencere Yeniden Boyutlandırıldı!",
    ["If you want all windows to be this size, you can set the default window size within WIM's options."] = "Tüm pencerelerin bu boyutta olmasını istiyorsanız, WIM'in seçeneklerinden varsayılan pencere boyutunu ayarlayabilirsiniz.",
    ["Creating Tab Groups"] = "Sekme Grupları Oluşturma",
    ["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = "Bir pencereyi <Shift ile tıklayıp> diğerinin üzerine sürükleyerek iki veya daha fazla pencereyi birlikte gruplayabilirsiniz.",
    ["Resizing Windows"] = "Pencereleri Yeniden Boyutlandırma",
    ["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = "<Shift> tuşunu basılı tutup pencerenin sağ alt köşesini sürükleyerek pencereyi yeniden boyutlandırabilirsiniz.",
    ["Demo Window"] = "Demo Penceresi",
    ["<Shift-Click> to close window."] = "Pencereyi kapatmak için <Shift-Tıkla>.",
    ["Message Window Hidden"] = "Mesaj Penceresi Gizli",
    ["WIM's message window has been hidden to WIM's Minimap Icon. If you want to end a conversation, you may do so by <Shift-Clicking> the close button."] = "WIM'in mesaj penceresi WIM'in Minimap Simgesine gizlenmiştir. Bir konuşmayı sonlandırmak isterseniz, bunu kapat düğmesine <Shift-Tıklayarak> yapabilirsiniz.",
    ["Default"] = "Varsayılan",
    ["%s is Away From Keyboard: %s"] = "%s Klavyeden Uzakta: %s",
    ["%s does not wish to be disturbed: %s"] = "%s rahatsız edilmek istemiyor: %s",
    ["Right-Mouse Click!"] = "Sağ Fare Tıklaması!",
    ["There might be useful tools hidden under the message box. Right-Click to see them!"] = "Mesaj kutusunun altına gizlenmiş faydalı araçlar olabilir. Onları görmek için Sağ Tıklayın!",


    -- Options.lua --
    ["Display WIM's options."] = "WIM'in seçeneklerini görüntüleyin.",
    ["Resetting WIM will clear all of your settings!"] = "WIM'i sıfırlamak tüm ayarlarınızı temizleyecektir!",
    ["Reset all options to default."] = "Tüm seçenekleri varsayılana sıfırlayın.",

    -- CoreOptions --
    ["Created By:"] = "Tarafından Oluşturuldu:",
    ["Special Thanks:"] = "Özel Teşekkürler:",
    ["Welcome!"] = "Hoş geldiniz!",
    ["Enable WIM"] = "WIM'i Etkinleştir",
    ["Display Minimap Icon"] = "Minimap Simgesini Görüntüle",
    ["<Right-Click> to show unread messages."] = "Okunmamış mesajları göstermek için <Sağ-Tıkla>.",
    ["Display Tutorials"] = "Öğreticileri Görüntüle",
    ["Reset Tutorials"] = "Öğreticileri Sıfırla",
    ["Credits"] = "Jenerik",
    ["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = "Bu, hem ifadeler hem de URL adresleri içeren uzun bir mesajdır 8).",
    ["Message Formatting"] = "Mesaj Biçimlendirme",
    ["Manipulate how WIM displays messages."] = "WIM'in mesajları nasıl görüntüleyeceğini değiştirin.",
    ["Preview"] = "Önizleme",
    ["Display Time Stamps"] = "Zaman Damgalarını Görüntüleme",
    ["Display Emoticons"] = "İfadeleri Göster",
    ["Display URLs as Links"] = "URL'leri Bağlantı Olarak Görüntüleme",
    ["Indent long messages."] = "Uzun mesajları girintileyin.",
    ["Bracket names."] = "Ayraç isimleri.",
    ["Window Behavior"] = "Pencere Davranışı",
    ["You can control how windows behave while you are in different situations."] = "Siz farklı durumlarda iken pencerelerin nasıl davranacağını kontrol edebilirsiniz.",
    ["Intercept Slash Commands"] = "/ Komutlarını Engelleme",
    ["Obey autofocus rules when opening frames via the menu. (autofocus if unchecked)"] = "Çerçeveleri menü aracılığıyla açarken odaklama kurallarına uy.\n (işaretlenmemişse otomatik odaklama)",
    ["Use the same rules for all states."] = "Tüm durumlar için aynı kuralları kullanın.",
    ["Behaviors for state"] = "Duruma göre tepkiler",
    ["Pop-Up window when message is sent."] = "Mesaj gönderildiğinde pencere açılır.",
    ["Pop-Up window when message is received."] = "Mesaj alındığında pencere açılır.",
    ["Auto focus a window when it is shown."] = "Bir pencere gösterildiğinde otomatik odaklama.",
    ["Keep focus on window after sending a message."] = "Bir mesaj gönderdikten sonra odağı pencerede tut.",
    ["Suppress messages from the default chat frame."] = "Varsayılan sohbet çerçevesinden gelen mesajları gizle.",
    ["Window Settings"] = "Pencere Ayarları",
    ["Some settings may be limited by certain skins."] = "Bazı ayarlar belirli görünümler tarafından sınırlandırılabilir.",
    ["Default Width"] = "Varsayılan Genişlik",
    ["Default Height"] = "Varsayılan Yükseklik",
    ["Window Scale"] = "Pencere Ölçeği",
    ["Window Alpha"] = "Pencere Şeffaflığı",
    ["Set Window Spawn Location"] = "Pencere Belirme Konumunu Ayarla",
    ["Up"] = "Yukarı",
    ["Down"] = "Aşağı",
    ["Left"] = "Sol",
    ["Right"] = "Sağ",
    ["Cascade overlapping windows."] = "Üst üste binen pencereleri kademelendirin.",
    ["Ignore arrow keys in message box."] = "Mesaj kutusundaki ok tuşlarını yoksay.",
    ["Allow <ESC> to hide windows."] = "Pencereleri gizlemek için <ESC>'ye izin ver.",
    ["Display Settings"] = "Ekran Ayarları",
    ["Configure general window display settings."] = "Genel pencere görüntüleme ayarlarını yapılandırın.",
    ["Window Skin:"] = "Pencere Kaplaması:",
    ["Version"] = "Sürüm",
    ["Color: System Messages"] = "Renk: Sistem Mesajları",
    ["Color: Error Messages"] = "Renk: Hata Mesajları",
    ["Color: URL - Web Addresses"] = "Renk: URL - Web Adresleri",
    ["Color: History Messages Sent"] = "Renk: Geçmiş Gönderilen Mesajlar",
    ["Color: History Messages Received"] = "Renk: Geçmiş Alınan Mesajlar",
    ["Use colors suggested by skin."] = "Kaplama tarafından önerilen renkleri kullanın.",
    ["Enable window fading effects."] = "Pencere solma efektlerini etkinleştirin.",
    ["Enable window animation effects."] = "Pencere animasyon efektlerini etkinleştirin.",
    ["Display item links when hovering over them."] = "Öğelerin üzerine gelindiğinde öğe bağlantılarını görüntüleyin.",
    ["Fonts"] = "Yazı tipleri",
    ["Configure the fonts used in WIM's message windows."] = "WIM'in mesaj pencerelerinde kullanılan yazı tiplerini yapılandırın.",
    ["Font Outline"] = "Yazı Tipi Dış Hatları",
    ["Thin"] = "İnce",
    ["Thick"] = "Kalın",
    ["Use font suggested by skin."] = "Kaplamanın önerdiği yazı tipini kullanın.",
    ["Chat Font Size"] = "Sohbet Yazı Tipi Boyutu",
    ["Configure general display settings when dealing with whispers."] = "Fısıltılarla uğraşırken genel görüntüleme ayarlarını yapılandırın.",
    ["Color: Messages Sent"] = "Renk: Gönderilen Mesajlar",
    ["Color: Messages Received"] = "Renk: Alınan Mesajlar",
    ["Use colors suggested by skin."] = "Kaplama tarafından önerilen renkleri kullanın.",
    ["Display user class icons and details."] = "Kullanıcı sınıfı simgelerini ve ayrıntılarını görüntüleyin.",
    ["Requires who lookups."] = "Kişi sorgulaması gerektirir.",
    ["Display Shortcut Bar"] = "Kısayol Çubuğunu Görüntüle",
    ["Allow"] = "İzin ver",
    ["Ignore"] = "Görmezden gel",
    ["Block"] = "Engelle",
    ["Filtering"] = "Filtreleme",
    ["Filtering allows you to control which messages are handled as well as how they are handled by WIM."] = "Filtreleme, hangi mesajların işleneceğini ve WIM tarafından nasıl işleneceğini kontrol etmenizi sağlar.",
    ["Enable Filtering"] = "Filtrelemeyi Etkinleştir",
    ["Protected"] = "Korumalı",
    ["Action:"] = "Eylem:",
    ["Occurrences:"] = "Oluşumlar:",
    ["Delete Filter"] = "Filtre Sil",
    ["History"] = "Geçmiş",
    ["WIM can store conversations to be viewed at a later time."] = "WIM, konuşmaları daha sonra görüntülenmek üzere saklayabilir.",
    ["Enable History"] = "Geçmişi Etkinleştir",
    ["Messages"] = "Mesajlar",
    ["Preview history inside message windows."] = "Mesaj pencerelerinin içindeki geçmişi önizleyin.",
    ["Record Whispers"] = "Fısıltıları Kaydet",
    ["Record Friends"] = "Arkadaşları Kaydet",
    ["Record Guild"] = "Guildi Kaydet",
    ["Record Everyone"] = "Herkesi Kaydet",
    ["Record Chat"] = "Sohbeti Kaydet",
    ["Maintenance"] = "Bakım",
    ["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = "Geçmiş kayıtlarınızın çok büyümesine izin vermek oyunun performansını etkileyecektir, bu nedenle aşağıdaki seçenekleri kullanmanız önerilir.",
    ["Save a maximum number of messages per person."] = "Kişi başına maksimum sayıda mesaj kaydet.",
    ["%d |4Week:Weeks;"] = "%d |4Hafta:Haftalar;",
    ["Automatically delete old messages."] = "Eski mesajları otomatik olarak sil.",
    ["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = "WIM-2-WIM, WIM'li kullanıcıların normal fısıldaşmanın yapamayacağı şekilde etkileşime girmesini sağlayan bir özelliktir.",
    ["Enable WIM-2-WIM"] = "WIM-2-WIM'i Etkinleştir",
    ["Privacy"] = "Gizlilik",
    ["Restrict the data that is shared."] = "Paylaşılan verileri kısıtlayın.",
    ["Allow others to see me typing."] = "Başkalarının beni yazarken görmesine izin ver.",
    ["Allow others to see my location."] = "Başkalarının konumumu görmesine izin ver.",
    ["Main"] = "Temel",
    ["General"] = "Genel",
    ["User Level"] = "Kullanıcı Seviyesi",
    ["Windows will also be hidden when frames such as the world map are shown."] = "Dünya haritası gibi çerçeveler gösterildiğinde pencereler de gizlenecektir.",
    ["Sounds"] = "Sesler",
    ["Configure various sound events and how they are triggered."] = "Çeşitli ses olaylarını ve bunların nasıl tetikleneceğini yapılandırın.",
    ["Play sound when a whisper is received."] = "Bir fısıltı alındığında ses çalsın.",
    ["Play special sound for friends."] = "Arkadaşlar için özel ses çal.",
    ["Play special sound for battle.net friends."] = "Battle.net arkadaşları için özel ses çal.",
    ["Play special sound for guild members."] = "Guild üyeleri için özel ses çalın.",
    ["Play sound when a whisper is sent."] = "Bir fısıltı gönderildiğinde ses çal.",
    ["Allow others to see my talent spec."] = "Başkalarının yetenek özelliklerimi görmesine izin ver.",
    ["Window Strata:"] = "Pencere Tabakaları:",
    ["Unlock from Minimap"] = "Minimap'ten kilidi aç",
    ["Press <Tab> to advance to next tell target."] = "Bir sonraki söyleme hedefine ilerlemek için <Tab> tuşuna basın.",
    ["Force sounds when game sound is disabled."] = "Oyun sesi devre dışı bırakıldığında sesleri zorla.",
    ["Colorize names."] = "İsimleri renklendirin.",
    ["Clamp window to screen."] = "Pencereyi ekrana kenetleyin.",
    ["Group with whisper windows."] = "Fısıltı pencereleriyle grup.",
    ["Color: BNet Messages Sent"] = "Renk: BNet Mesajları Gönderildi",
    ["Color: BNet Messages Received"] = "Renk: BNet Mesajları Alındı",

    -- TabManagement.lua --
    ["Tab Management"] = "Sekme Yönetimi",
    ["Automatically manage your open windows and place them into appropriate tab groups."] = "Açık pencerelerinizi otomatik olarak yönetin ve uygun sekme gruplarına yerleştirin.",
    ["Automatically group whispers."] = "Fısıltıları otomatik olarak gruplandırın.",
    ["Place friends in their own group."] = "Arkadaşlarınızı kendi gruplarına yerleştirin.",
    ["Place guild members in their own group."] = "Guild üyelerini kendi gruplarına yerleştirin.",
    ["Automatically group chat windows."] = "Sohbet pencerelerini otomatik olarak gruplandır.",
    ["Does not apply to windows already opened."] = "Önceden açılmış pencereler için geçerli değildir.",


    -- Talent Specs --
    ["Affliction"] = "true",
    ["Arcane"] = "true",
    ["Arms"] = "true",
    ["Assassination"] = "true",
    ["Balance"] = "true",
    ["Beast Mastery"] = "true",
    ["Blood"] = "true",
    ["Brewmaster"] = "true",
    ["Combat"] = "true",
    ["Demonology"] = "true",
    ["Destruction"] = "true",
    ["Discipline"] = "true",
    ["Elemental"] = "true",
    ["Enhancement"] = "true",
    ["Feral Combat"] = "true",
    ["Fire"] = "true",
    ["Frost"] = "true",
    ["Fury"] = "true",
    ["Guardian"] = "true",
    ["Holy"] = "true",
    ["Hybrid"] = "true",
    ["Marksmanship"] = "true",
    ["Mistweaver"] = "true",
    ["Protection"] = "true",
    ["Restoration"] = "true",
    ["Retribution"] = "true",
    ["Shadow"] = "true",
    ["Subtlety"] = "true",
    ["Survival"] = "true",
    ["Unholy"] = "true",
    ["Windwalker"] = "true",
    ["Havok"] = "true",
    ["Vengeance"] = "true",

    -- ChangeLog.lua --
    ["Change Log"] = "Değişiklikler Günlüğü",
    ["View WIM's change log."] = "WIM'in değişiklik günlüğünü görüntüleyin.",
    ["Available For Download!"] = "İndirmek için hazır!",

    -- Filters.lua --
    ["Show Alert"] = "Uyarı Göster",
    ["WIM has blocked a message from %s."] = "WIM %s tarafından gelen bir mesajı engelledi.",
    ["View Blocked Message"] = "Engellenen Mesajı Görüntüle",
    ["Blocked Message"] = "Engellenen Mesaj",

    -- MinimapIcon.lua
    ["Show Unread Messages"] = "Okunmayan Mesajları Göster",
    ["Show All Windows"] = "Tüm Pencereleri Göster",
    ["Hide All Windows"] = "Tüm Pencereleri Gizle",

    --Emoticons.lua
    ["Also"] = "Ayrıca",
    ["More"] = "Daha fazla",
    ["Emoticons"] = "İfadeler",

    --Expose.lua
    ["Your conversations have been hidden in order to clear your screen while in combat. To disable this feature type"] = "Savaş sırasında ekranınızı temizlemek için konuşmalarınız gizlenmiştir. Bu özelliği devre dışı bırakmak için",
    ["Expose"] = "Expose",
    ["Expose is a Mac OS X inspired feature which enables you to quickly clear your screen of windows and then restore them back to their original position."] = "Expose, ekranınızdaki pencereleri hızlı bir şekilde temizlemenizi ve ardından orijinal konumlarına geri getirmenizi sağlayan Mac OS X'ten ilham alan bir özelliktir.",
    ["Auto hide/restore windows during combat."] = "Savaş sırasında pencereleri otomatik gizle/geri yükle.",
    ["Delay if I am typing a message."] = "Bir mesaj yazıyorsam geciktir.",
    ["Border Size"] = "Kenarlık Boyutu",
    ["Only while in an instance."] = "Sadece bir olay içindeyken.",
    ["Show Border"] = "Kenarlığı Göster",
    ["Animation Direction:"] = "Animasyon Yönü:",

    --ChatEngine.lua
    ["WIM will manage this chat type within its own message windows."] = "WIM bu sohbet türünü kendi mesaj pencereleri içinde yönetecektir.",
    ["Show Minimap Alerts"] = "Minimap Uyarılarını Göster",
    ["Never pop-up on my screen."] = "Benim ekranımda hiç açılmıyor.",
    ["Never suppress messages."] = "Mesajları asla bastırma.",
    ["Include emotes."] = "İfadeleri dahil et.",
    ["Have WIM monitor this channel."] = "WIM'in bu kanalı izlemesini sağlayın.",
    ["Never Pop"] = "Asla Açılmaz",
    ["Never have this window pop-up on my screen."] = "Bu pencere asla ekranımda açılmaz.",
    ["Never Supress"] = "Asla Bastırmayın",
    ["Never suppress messages from the default chat frame."] = "Varsayılan sohbet çerçevesinden gelen mesajları asla bastırmayın.",
    ["Show unread message alert on minimap."] = "Mini haritada okunmamış mesaj uyarısını gösterin.",
    ["No History"] = "Geçmiş Yok",
    ["Do not record history for this channel."] = "Bu kanal için geçmişi kaydetmeyin.",
    ["World Chat"] = "Dünya Sohbeti",
    ["Custom Chat"] = "Özel Sohbet",
    ["Chat"] = "Sohbet",
    ["Play special sound for %s."] = "%s için özel ses çal.",
    ["Play sound when a message is received."] = "Bir mesaj alındığında ses çal.",
    ["Play sound when a message is sent."] = "Bir mesaj gönderildiğinde ses çal.",
    ["Do not play sounds for this channel."] = "Bu kanal için ses çalmayın.",
    ["No Sound"] = "Ses Yok",
    ["Sensitivity"] = "Hassasiyet",
    ["Enable WorldFrame Click Detection."] = "WorldFrame Tıklama Algılamasını Etkinleştir.",
    ["The UI must be reloaded in order to disable this module fully. Reload UI now?"] = "Bu modülü tamamen devre dışı bırakmak için kullanıcı arayüzü yeniden yüklenmelidir. UI yeniden yüklensin mi?",

    --OffScreenTracker.lua
    ["WIM Window Off Screen"] = "WIM Penceresi Ekran Dışında",
    ["Click to reposition."] = "Yeniden konumlandırmak için tıklayın.",

    --Misc
    ["WIM has detected that you are playing on a private server. Some servers can not process ChatAddonMessages. Would you like to enable them anyway?"] = "WIM, özel bir sunucuda oynadığınızı tespit etti. Bazı sunucular ChatAddonMessages komutlarını işleyemez. Yine de onları etkinleştirmek ister misiniz?",

};

-- wait for variables to be loaded, and then add locale.
WIM.AddLocale("trTR", translations);
